### ISSUE TITLE
Option to hide missing images

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-imagebar#100]
There are a lot of media files that have somehow disappeared from my media directory.
This module is a convenient way for me to find them (red box saying "404").
But I don't want to show those to people who can't do anything about it.
So it would be convenient to be able to select which roles are allowed to see those.
Dank je wel!

**Comment by WGroleau** [comment]
Might also mention on the settings page how it chooses which of the enabled images it will display.

**Comment by JustCarmen** [comment]
> But I don't want to show those to people who can't do anything about it.

Normally, this will not happen. Only administrators can access the module configuration page.
Those images are not visible at the front end.

I know what you are doing. From time to time I also use this module to find 404 images. But this module is not an image manager and I have no intention of turning it into one.

Therefore I consider this request beyond the scope of this module.
