### ISSUE TITLE
Context sensitive display

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-imagebar#101]
Another thing that might be nice would be an option on an INDI of FAM page to limit the images shown to OBJE contained in that FAM or INDI.  If there aren't enough to fill the bar, add others at random).

**Comment by JustCarmen** [comment]
No, I don't think this is a good idea. In many cases there will not be enough images to fill the image bar.  Also, the image bar is meant to be a showcase of the entire website and should not be limited to just one individual or family. There is already an album tab module that does just that.
