### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-imagebar#103]
Followed this instruction:
"Unpack the zip file and place the folder jc-fancy-imagebar in the modules_v4 folder of webtrees"

Next time I visited my site: 
"Fatal error: Cannot declare class JustCarmen\Webtrees\Module\FancyImagebar\FancyImagebarModule, because the name is already in use in /var/www/html/un/unigen.us/modules_v4/webtrees-fancy-imagebar-main/FancyImagebarModule.php on line 35"

**Comment by WGroleau** [comment]
Weirder still: restoring the entire `modules_v4` from earlier backup still gets same error.

**Comment by JustCarmen** [comment]
I think you are using a source code zip file (automatically added by Github for development).

Use the stable release version instead.

Download it from here: https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/latest

or if you are in doubt which zip file to take, then go to my website and download it from there:
https://justcarmen.nl/modules-webtrees-2/fancy-imagebar/

**Comment by WGroleau** [comment]
On Apr 23, 2022, at 21:55, Carmen ***@***.***> wrote:
> Use the stable release version instead.
> 
> Download it from here: https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/latest

I just installed the image bar from here, then …

> or if you are in doubt which zip file to take, then go to my website and download it from there:
> https://justcarmen.nl/modules-webtrees-2/fancy-imagebar/

I installed research links from https://justcarmen.nl/modules-webtrees-2/fancy-research-links/

Went to the site in the browser and saw

Fatal error: Declaration of JustCarmen\Webtrees\Module\FancyResearchLinks\FancyResearchLinksModule::sidebarTitle(): string must be compatible with Fisharebest\Webtrees\Module\ModuleSidebarInterface::sidebarTitle(Fisharebest\Webtrees\Individual $individual): string in /var/www/html/un/unigen.us/modules_v4/jc-fancy-research-links/FancyResearchLinksModule.php on line 215

But it says webtrees 2.0 and I have 2.1  So I’m not surprised.  I’ll delete it again.

-- 
Wes Groleau
Wandering Weirdo, 伟思礼

“Ideas are more dangerous than guns.
We would not let our enemies have guns;
why would we let them have ideas?”
    — Jozef Stalin

**Comment by JustCarmen** [comment]
Both are not compatible with 2.1 yet. I am working on it.

**Comment by JustCarmen** [comment]
This module is now compatible with webtrees 2.1

https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/tag/2.2.0
