### ISSUE TITLE
Error when accessing parameters

### ISSUE THREAD

**Issue by patrickfaivre** [JustCarmen/webtrees-fancy-imagebar#106]
jc-fancy-imagebar-2.2.0 on Webtrees 2.1.2 : the display is fine.
But I can't access the settings: see the error message in the attachment.

[error_jc-fancy-imagebar.txt](https://github.com/JustCarmen/webtrees-fancy-imagebar/files/8646418/error_jc-fancy-imagebar.txt)

**Comment by JustCarmen** [comment]
I think this is the same error as #96 which was solved I thought.

Is it possible that you have deleted a tree recently?
Apparently the check that the last-tree-id setting in the database belongs to an existing tree fails (again).

You could remove the setting from the database table wt_module_setting. Look for module_name: fancy-imagebar and setting_name: last-tree-id. This should solve your problem for now. That will give me time to look for a better solution.

**Comment by fisharebest** [comment]
Hi Carmen - I looked at the `TreeService::find()` code in webtrees.

It relies on `assert()`, which can be disabled.  If it wasn't present, you would get the error that was reported on the forum.

I need to replace it with an `if(null) { throw }`

**Comment by JustCarmen** [comment]
So, if I understand you correctly this needs to be adjusted in webtrees.

Should I create a new issue?

**Comment by patrickfaivre** [comment]
Hello Carmen,
There was no tree deleted.
The fancy-imagebar module does not exist; there is only the _jc-theme-justlight_ module (see attachment).
Sincerely

[wt_module_setting.txt](https://github.com/JustCarmen/webtrees-fancy-imagebar/files/8667305/wt_module_setting.txt)

**Comment by JustCarmen** [comment]
As a workaround I've made a small change to the code. Would you please test if this works?

Just replace the file FancyImagebarModule.php on the server.

**Comment by JustCarmen** [comment]
https://raw.githubusercontent.com/JustCarmen/webtrees-fancy-imagebar/main/FancyImagebarModule.php

Right mouse click 'save link as'

**Comment by patrickfaivre** [comment]
I replaced the file FancyImagebarModule.php
There is still the error message (see attachment).

[error_jc-fancy-imagebar.txt](https://github.com/JustCarmen/webtrees-fancy-imagebar/files/8673241/error_jc-fancy-imagebar.txt)

**Comment by JustCarmen** [comment]
Okay, good to know. I can't reproduce the error what makes it hard to solve. I think we have to wait for @fisharebest then.

**Comment by fisharebest** [comment]
https://github.com/fisharebest/webtrees/commit/960991e4e5e143df3ec2250f2ba00514bc02827e

If this doesn't help, then I don't think the issue is at my end.

**Comment by JustCarmen** [comment]
Thanks @fisharebest  for your help with this matter.

@patrickfaivre because I can't reproduce the error myself I need you to test it for me.

Would you please download this file: https://github.com/fisharebest/webtrees/raw/960991e4e5e143df3ec2250f2ba00514bc02827e/app/Services/TreeService.php

And put it in the webtrees folder app/Services on your server.

Let me know the results.

I'm away for a couple of days without my laptop, so I won't respond until next week.

**Comment by patrickfaivre** [comment]
With this version of TreeService.php, jc-fancy-imagebar works perfectly! Thanks to you!

**Comment by AndreasRauhut** [comment]
Me too, I can access the settings, but when I try to save changes I get an error screen.  "Internal Server Error"

I tried to replace the original TreeService.php of the freshly installed  jc-fancy-imagebar-2.2.0 by the above proposed version, but that didn't change anything visible to me.
