### ISSUE TITLE
Feature Request: Add to user page

### ISSUE THREAD

**Issue by JesseWebDotCom** [JustCarmen/webtrees-fancy-imagebar#109]
This module is fantastic. Is there any way to add it to user pages as well as the home page?  I have a custom theme so I can add it there as well if you guide me.

Thanks

**Comment by JustCarmen** [comment]
By default, the Fancy imagebar is displayed on every page. However, there is an option on the configuration page to show the imagebar only on the homepage. I think you (accidentally) set that option to 'yes'. Change it to 'no'.

The Fancy imagebar works on all themes, even custom ones. But you might need some extra styling. For this, use the class '.jc-fancy-imagebar' in your stylesheet.
