### ISSUE TITLE
ORDER BY RAND() LIMIT N can be very slow for large tables.

### ISSUE THREAD

**Issue by fisharebest** [JustCarmen/webtrees-fancy-imagebar#116]
Apologies if you already saw this forum post:
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37581-slow-performance-2-1-8#96849

There are various ways to select random rows from a table.
The one provided by the laravel database library is probably the slowest...

**Comment by JustCarmen** [comment]
Saw the forum post indeed. I forgot to reference this issue, but I've fixed it with this commit: 53487bb9ccede0971f936f9d9040e004244c748a.

The randomization and limitation is now done after the data is pulled from the database but before processing the images.
