### ISSUE TITLE
Type Error at FancyImagebarModule.php:485

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-imagebar#117]
I got an error after installing the latest released version.

> TypeError: substr(): Argument #3 ($length) must be of type ?int, bool given in /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:485 Stack trace: #0 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(485): substr() #1 [internal function]: JustCarmen\Webtrees\Module\FancyImagebar\FancyImagebarModule->JustCarmen\Webtrees\Module\FancyImagebar\{closure}() #2 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/illuminate/collections/Collection.php(695): array_map() #3

**Comment by LarsRabe** [comment]
I can confirm this

**Comment by JustCarmen** [comment]
I cannot reproduce this, but I made a small adjustment. Would one of you please test it before I release this. Thanks!

**Comment by LarsRabe** [comment]
For me it works now, but I only have a few images by now. 
Lets see what @hartenthaler has to say

**Comment by hartenthaler** [comment]
There is no error in my test system and in my productive system anymore. Thank you!
