### ISSUE TITLE
Performance suggestions

### ISSUE THREAD

**Issue by fisharebest** [JustCarmen/webtrees-fancy-imagebar#12]
Hi Carmen - I've just been investigating some performance issues, which came from the fancy image bar.

The user had not configured any images, so the module is selecting all of them using `$this->dbMedia()`.
https://github.com/JustCarmen/fancy_imagebar/blob/1.7.11/app/FancyImagebarClass.php#L373

For his site, this query fetches approx 1000 media XREFs.

Then we call `Media::getInstance()` without the third parameter, which means we must query the database to find the GEDCOM
https://github.com/JustCarmen/fancy_imagebar/blob/1.7.11/app/FancyImagebarClass.php#L384

Suggestion.  Fetch the `m_gedcom` field in the original database call, and pass it to `getInstance()`.  This stops the database call.

This would reduce the number of database calls from 1001 to 1.

For non-admins, we must then do privacy checks on these objects.
https://github.com/JustCarmen/fancy_imagebar/blob/1.7.11/app/FancyImagebarClass.php#L385

The privacy checks require that we fetch each record linked to a media object.  This is another 1000 queries (or more).

You could reduce this by fetching the linked individuals (including the `i_gedcom data`) in a single query, and then calling `Individual::getInstance()` with the third parameter.

Now, you would have just one DB call for all linked individuals.

(Repeat for linked families, sources, etc.)

**Comment by JustCarmen** [comment]
This is solved in [the first release of this module for webtrees 2](https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.0.7). Performance is very much improved.

The webtrees 1 version of the module will not undergoing major changes anymore.
