### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-fancy-imagebar#120]
Changes from 2.2.1 slow down the site again.
Please revert random selection back to db - access.

**Comment by JustCarmen** [comment]
It was on [Gregs' advice](https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/116) I removed random and limit from the database query for a better performance. I think it works.

I don't think reverting random selection back to db access will make the difference.

**Comment by arbor95** [comment]
It does make a difference, else I did not complain. I will take the time for my site (1367 images) and give you the numbers to compare.
I am surprised that getting all images and then do random selection should be quicker than getting only some random images. I do not believe.
Perhaps a pre randomization (as idea, using record numbers from within the number of images or as Greg writes using "primary keys") may be the best solution. 
Did you use the "primary keys" ? As much as I see, you don't.

**Comment by LarsRabe** [comment]
@JustCarmen 
I can confirm the slower behaviour with the 2.2.2-release on a test instance with 1000+ images too. I think you and Greg should think this new.

**Comment by arbor95** [comment]
> @JustCarmen I can confirm the slower behaviour with the 2.2.2-release on a test instance with 1000+ images too. I think you and Greg should think this new.
As I have written: You did not correctly follow Gregs proposal.

**Comment by JustCarmen** [comment]
Sorry but I don't experience a slower behavior. I've tested it in my local test site and in my case the 2.2.2 version is significantly faster then the 2.2.0 version.

> Did you use the "primary keys" ? As much as I see, you don't.
Greg proposed to fetch all the primary keys, use PHP to select them using array_rand(), and then fetch just those rows in a second query. But that means rewriting quite a bit of code as far as I can see. I didn't had the time for that. So I just use one query and randomize the resulting array afterwards. In all my tests this was faster than before.

But that doesn't mean that the code can't be further optimized. But you have to realize that I am not an expert. I'm just someone who happens to know enough about coding to customize webtrees to my liking. And others may take advantage of it. But I can't keep everyone happy.

**Comment by arbor95** [comment]
So we are now 2 against one.
Does the result depend on the number of records?
Perhaps you did the test, when you are logged in?

**Comment by LarsRabe** [comment]
@JustCarmen
I tested with a local site on my PC and again on my actual webserver. On my local site I can, like you, see that 2.2.2 is a tiny bit faster than 2.2.0. But, on the other hand, on my actual webserver the 2.2.2 is significant slower. As far as I can tell, my local server and the server at my hoster are configured the same.

**Comment by JustCarmen** [comment]
I will look into this. I'll see what I can do.

**Comment by arbor95** [comment]
Thank you in advance.

**Comment by JustCarmen** [comment]
Thanks for the suggestion.  As soon as I have some spare time I will try this out.

**Comment by arbor95** [comment]
I found this, which may be helpfull:
https://www.warpconduit.net/2011/03/23/selecting-a-random-record-using-mysql-benchmark-results/

**Comment by JustCarmen** [comment]
Hope this helps

**Comment by arbor95** [comment]
2.2.3-dev is fine
