### ISSUE TITLE
Timeout on setup

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-fancy-imagebar#121]
On setup,
when I show all images
a timeout occures and I get logged off.

For me a solution would be to show the images to select only after havin pressed a button (which opens a new page).

**Comment by JustCarmen** [comment]
Are you talking about the image table on the configuration page?

**Comment by arbor95** [comment]
Yes

**Comment by arbor95** [comment]
2.3.0-dev is fine
