### ISSUE TITLE
Fatal error with Version 2.3.0

### ISSUE THREAD

**Issue by webtrees-pesz** [JustCarmen/webtrees-fancy-imagebar#123]
Hi Carmen,

I am using webtrees V2.1.17 and fancy-imagebar 2.3.0.
When I start webtrees with your new version 2.3.0 I get immidiately folowing error. With V 2.2.2 every thing is running fine.

Error: Call to a member function canShow() on null in /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:417 Stack trace: #0 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(271): JustCarmen\Webtrees\Module\FancyImagebar\FancyImagebarModule->fancyImagebar() #1 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(207): JustCarmen\Webtrees\Module\FancyImagebar\FancyImagebarModule->bodyContent() #2 [internal function]: Fisharebest\Webtrees\View::{closure}() #3 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/illuminate/collections/Collection.php(695): array_map() #4 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(208): Illuminate\Support\Collection->map() #5 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/View.php(183): include('...') #6 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/View.php(278): Fisharebest\Webtrees\View->render() #7 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #8 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/ViewResponseTrait.php(54): view() #9 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/RequestHandlers/UserPage.php(84): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse() #10 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle() #11 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process() #12 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle() #13 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process() #14 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher->handle() #15 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process() #16 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle() #17 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process() #18 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle() #19 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process() #20 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/AuthLoggedIn.php(51): Middleland\Dispatcher->handle() #21 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthLoggedIn->process() #22 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle() #23 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process() #24 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #25 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #26 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/Router.php(163): Fisharebest\Webtrees\Webtrees::dispatch() #27 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process() #28 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle() #29 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process() #30 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle() #31 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process() #32 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle() #33 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #34 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle() #35 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process() #36 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #37 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #38 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #39 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process() #40 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle() #41 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process() #42 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle() #43 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process() #44 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle() #45 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process() #46 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle() #47 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #48 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #49 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #50 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #51 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #52 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle() #53 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #54 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/BadBotBlocker.php(287): Middleland\Dispatcher->handle() #55 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #56 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #57 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #58 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #59 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #60 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #61 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #62 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #63 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #64 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #65 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #66 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #67 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #68 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #69 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #70 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #71 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #72 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #73 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #74 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #75 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #76 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #77 {main}

**Comment by JustCarmen** [comment]
I cannot reproduce the error, but looking into the code I might have found what caused this. Can you confirm if this solves your issue?

**Comment by webtrees-pesz** [comment]
Hello Carmen,

thanks for the fast support. The problem seems to be solved.
