### ISSUE TITLE
Error on display media list in control panel

### ISSUE THREAD

**Issue by tronsmit** [JustCarmen/webtrees-fancy-imagebar#132]
I'm using jc-fancy-imagebar v 2.3.1 on webtrees 2.1.8

I have the same problem as mentioned in closed issue #131 

`Call to a member function mediaFiles() on null …/modules_v4/jc-fancy-imagebar/resources/views/media-table.phtml:56`
`#0 …/app/View.php(183): include()`
`#1 …/app/View.php(278): Fisharebest\Webtrees\View->render()`
`#2 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()`
`#3 …/modules_v4/jc-fancy-imagebar/resources/views/settings.phtml(108): view()`
`#4 …/app/View.php(183): include('/home/tronsmit/...')`
`#5 …/app/View.php(278): Fisharebest\Webtrees\View->render()`
`#6 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()`
`#7 …/app/Http/ViewResponseTrait.php(50): view()`
`#8 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(207): Fisharebest\Webtrees\Module\AbstractModule->viewResponse()`
`#9 …/app/Http/RequestHandlers/ModuleAction.php(85): JustCarmen\Webtrees\Module\FancyImagebar\FancyImagebarModule->getAdminAction()`
`#10 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()`

The error is triggered by selecting "display media list" in control panel

Unimportant notes:
- I would have skipped a few versions when upgrading imagebar and not have reset the preferences
- The imagebar display still works see https://genes.tronsmit.com
- in table module-setting changing 1-display-all from 1 to 0 at least let me see the admin config page again. Error repeats when toggling "Display the table..."
- tree-id 1 definitely has images
- selecting a tree without images, does not give the error, but just displays an empty table with no items

**Comment by JustCarmen** [comment]
Fixed: https://github.com/JustCarmen/webtrees-fancy-imagebar/pull/133
