### ISSUE TITLE
Fatal error: Declaration of JustCarmen

### ISSUE THREAD

**Issue by ManPython** [JustCarmen/webtrees-fancy-imagebar#137]
`Fatal error: Declaration of JustCarmen\WebtreesAddOns\FancyImagebar\FancyImagebarModule::getConfigLink() must be compatible with Fisharebest\Webtrees\Module\ModuleConfigInterface::getConfigLink(): string in E:\xampp-windows-x64-8.1.12-0-VS16\htdocs\webtrees\modules_v4\fancy_imagebar\module.php on line 106`

webtrees-2.1.18

**Comment by JustCarmen** [comment]
It looks like you are trying to use a really old version of the Fancy Imagebar for webtrees 1 on webtrees 2.

To solve this you should upgrade to the latest version of the Fancy Imagebar: https://justcarmen.nl/modules-webtrees-2/fancy-imagebar/

**Comment by ManPython** [comment]
I downloaded from github.

From your link working.
