### ISSUE TITLE
Image Stuck

### ISSUE THREAD

**Issue by angelocorbo** [JustCarmen/webtrees-fancy-imagebar#142]
Had an image deleted, but it persists showing up, although is no where to be found in either album or media. It's become an orphan reference. What's intriguing is that even after deleting the physical .jpg in the server, it persists possibly cached. The end result is that clicking settings in the fancybar module returns the error I've attached. 
[fancyImagebarError.pdf](https://github.com/user-attachments/files/16395644/fancyImagebarError.pdf)

**Comment by JustCarmen** [comment]
That shouldn't happen. Try deleting the fancy imagebar cache folder (data/fib-cache), to see if it helps.

**Comment by angelocorbo** [comment]
I had already tried deleting the offending photo from the directory and it stopped showing up. Now, trying to open the module preferences (wrench link) persists erroring out with output sent earlier (fancyImagebarError.pdf).  Not sure what may be causing it.

**Comment by JustCarmen** [comment]
Sorry I didn't read the error message properly. I now notice you are using the development version in stead of the latest stable release. Please download the latest release from [here](https://justcarmen.nl/modules-webtrees-2/fancy-imagebar/) or [here](https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/latest).

Upload the folder jc-fancy-imagebar to the modules_v4 folder and remove the folder webtrees-fancy-imagebar-main completely.

**Comment by JustCarmen** [comment]
I guess this issue is solved. if not, you can open a new issue.
