### ISSUE TITLE
not compatible to webtrees 2.2.1

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/webtrees-fancy-imagebar#150]
On webtrees 2.2.1 with PHP 8.3 I just get this messag:

Fatal error in module: jc-fancy-imagebar
Error: Call to undefined function JustCarmen\Webtrees\Module\FancyImagebar\app()

**Comment by arbor95** [comment]
+1

**Comment by erdima** [comment]
Ciao.
Rielevo i seguente errore. (Gia segnalato da altri utenti).  Forse serve solo un piccolo aggiornamento de modulo.
fancy-imagebar   2.3.1
-Webtrees  2.2.1 
-Php 8.3.11, 
-MySQL 5.7
Grazie per il vostro lavoro.
----
Fatal error in module: jc-fancy-imagebar
Error: Call to undefined function JustCarmen\Webtrees\Module\FancyImagebar\app() in /web/htdocs/www.antenatidellecese.it/home/modules_v4/jc-fancy-imagebar/module.php:9 Stack trace: 
#0 /web/htdocs/www.antenatidellecese.it/home/app/Services/ModuleService.php(722): include() 
#1 /web/htdocs/www.antenatidellecese.it/home/app/Services/ModuleService.php(702): Fisharebest\Webtrees\Services\ModuleService::load() #2 [internal function]:

**Comment by JustCarmen** [comment]
It is fixed now: https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/0c54a5066e559afccb14e58275d70e289da0f4aa

**Comment by erdima** [comment]
Ora funziona  bene.
Grazie mille.
