### ISSUE TITLE
PB

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/webtrees-fancy-imagebar#36]
first of all thank you for this version of this module.
but when i want to use it i have this as a message.
I hope this can help you
[FancyImagepb.txt](https://github.com/JustCarmen/webtrees-fancy-imagebar/files/5281369/FancyImagepb.txt)

Thank again

**Comment by Fa10175** [comment]
to help you i have 2 trees i  select the right tree directory it's ok but if i change is not ok
on 1.7 you have possibility do define for each tree

**Comment by JustCarmen** [comment]
I cannot reproduce the error. I've tested it with two trees.  What webtrees version do you use? 

> on 1.7 you have possibility do define for each tree
Yes that's true, but I've simplified things and now the images that belongs to each tree are automatically added to the imagebar.

**Comment by Fa10175** [comment]
PHP Version 7.3.11
Webtrees 2.07

i dowload right now your lastest version from today after the modification Fix38
It works without error.
Great

**Comment by Fa10175** [comment]
If they are no connexion to a tree i still have the error (i have several trees no acces without a connexion)
I should disable the module imagebar
i  connect to a tree and  then i enable the module it's ok until logout

**Comment by JustCarmen** [comment]
I see. This is not ok. There should be checked whether a tree is accessible.
