### ISSUE TITLE
fancy-imagebar and webtrees themes

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-imagebar#39]
fancy-imagebar looks perfect with the most webtrees themes, but not with the following three themes (see screenshots using browser "Edge"):

- F.A.B. 
![fab](https://user-images.githubusercontent.com/6324175/94322329-859a2000-ff92-11ea-85a1-ccd69f2f86d7.jpg)

- Rural (custom)
For this theme, it would be very nice to use a filter for all the images to make them look brown as you see it in very old photos.
![rural](https://user-images.githubusercontent.com/6324175/94322351-9054b500-ff92-11ea-91b1-476a5fa9e4b9.jpg)

- Argon (custom)
![argon](https://user-images.githubusercontent.com/6324175/94322363-99de1d00-ff92-11ea-84a3-7ecbfae1d282.jpg)

I don't know if the adaptation has to be made in the module "fancy-imagebar" or in these three theme modules.

**Comment by JustCarmen** [comment]
I've tested the Fancy Imagebar in all default webtrees themes and in the JustLight theme. For those themes I've added the necessary styles.

The F.A.B. theme looks good on my site, but apparently not everywhere. I will look into it.

I didn't do any other custom themes. Styling can be done in the custom theme or inside this module. It shouldn't be hard to implement though.

**Comment by JustCarmen** [comment]
At your request I tried to install [the latest release of the Argon theme](https://github.com/jchue/argon-webtrees-theme/releases/tag/v0.2.0) to add some styling for the Fancy Imagebar, but the theme throws an error right after installation. It is not possible to install the Argon theme upon the latest webtrees.  So I will close this issue. You may reopen it whenever the theme is updated.
