### ISSUE TITLE
tree-based display

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/webtrees-fancy-imagebar#40]
my aborrescence of files is:
Webtrees / Data / firewall / tree 1 / Photo
and
Webtrees / Data / firewall / tree 2 / Photo

on configuration ImageBar, it's possible to select 
1)  firewall / tree 1
or 
2)  firewall / tree 2

because they are no tree configuration as 1.7 it's no possible to display for both tree.
another possibility is to be able to enter
 firewall
 ( but webtrees cannot give this kind of details)
another possibility  is to put what we want without suggestion

Thanks to find a solution

**Comment by JustCarmen** [comment]
You have a point here. Didn't think of that. In my configuration a per tree option was not necessary that's why I didn't bring it in wt-2.  But I will reconsider it.

**Comment by Fa10175** [comment]
for information
after installing version 2.0.7.1 each tree displays all the documents belonging to it of all types. (Good)
in the database in the wt_module_setting table the field has been added (FIB_OPTIONS)

Now I go to the module configuration to put the correct filter, in this table the following fields are added
![Capture](https://user-images.githubusercontent.com/10681601/94367735-d9b31a80-00e0-11eb-943f-cea2005ca8ad.JPG)

and after we only see the documents of one of the 2 trees.

I happy if this can help you

**Comment by Fa10175** [comment]
if in the wt_module_setting table I delete media-folder and subfolders it's ok

**Comment by Fa10175** [comment]
Thanks for this update.
it good until you logout .
i have this message:

[new 1.txt](https://github.com/JustCarmen/webtrees-fancy-imagebar/files/5321359/new.1.txt)
