### ISSUE TITLE
Php7.4 installation of this module reports an error

### ISSUE THREAD

**Issue by kexuebin** [JustCarmen/webtrees-fancy-imagebar#42]
Error: Call to a member function fullName() on null in /www/wwwroot/genleri.com/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:428 Stack trace: #0 /www/wwwroot/genleri.com/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(348): JustCarmen\Webtrees\Module\FancyImagebarModule->createFancyImagebar() #1 /www/wwwroot/genleri.com/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(209): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyImagebar() #2 /www/wwwroot/genleri.com/resources/views/layouts/default.phtml(190): JustCarmen\Webtrees\Module\FancyImagebarModule->bodyContent() #3 [internal function]: Fisharebest\Webtrees\View::{closure}() #4 /www/wwwroot/genleri.com/vendor/illuminate/support/Collection.php(1120): array_map() #5 /www/wwwroot/genleri.com/resources/views/layouts/default.phtml(191): Illuminate\Support\Collection->map() #6 /www/wwwroot/genleri.com/app/View.php(189): include('/www/wwwroot/zi...') #7 /www/wwwroot/genleri.com/app/View.php(286): Fisharebest\Webtrees\View->render() #8 /www/wwwroot/genleri.com/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make() #9 /www/wwwroot/genleri.com/app/Http/ViewResponseTrait.php(58): view() #10 /www/wwwroot/genleri.com/app/Http/RequestHandlers/TreePage.php(93): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->viewResponse() #11 /www/wwwroot/genleri.com/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->handle() #12 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process() #13 /www/wwwroot/genleri.com/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle() #14 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process() #15 /www/wwwroot/genleri.com/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle() #16 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process() #17 /www/wwwroot/genleri.com/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle() #18 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process() #19 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #20 /www/wwwroot/genleri.com/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch() #21 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process() #22 /www/wwwroot/genleri.com/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle() #23 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process() #24 /www/wwwroot/genleri.com/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle() #25 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #26 /www/wwwroot/genleri.com/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #27 /www/wwwroot/genleri.com/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #28 /www/wwwroot/genleri.com/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #29 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process() #30 /www/wwwroot/genleri.com/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle() #31 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process() #32 /www/wwwroot/genleri.com/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle() #33 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process() #34 /www/wwwroot/genleri.com/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle() #35 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process() #36 /www/wwwroot/genleri.com/app/Http/Middleware/RegisterFactories.php(73): Middleland\Dispatcher->handle() #37 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process() #38 /www/wwwroot/genleri.com/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle() #39 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #40 /www/wwwroot/genleri.com/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle() #41 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #42 /www/wwwroot/genleri.com/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle() #43 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process() #44 /www/wwwroot/genleri.com/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle() #45 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #46 /www/wwwroot/genleri.com/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle() #47 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process() #48 /www/wwwroot/genleri.com/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle() #49 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #50 /www/wwwroot/genleri.com/app/Http/Middleware/BadBotBlocker.php(213): Middleland\Dispatcher->handle() #51 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #52 /www/wwwroot/genleri.com/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle() #53 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process() #54 /www/wwwroot/genleri.com/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle() #55 /www/wwwroot/genleri.com/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #56 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #57 /www/wwwroot/genleri.com/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #58 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #59 /www/wwwroot/genleri.com/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle() #60 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #61 /www/wwwroot/genleri.com/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle() #62 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #63 /www/wwwroot/genleri.com/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle() #64 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #65 /www/wwwroot/genleri.com/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #66 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #67 /www/wwwroot/genleri.com/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle() #68 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process() #69 /www/wwwroot/genleri.com/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #70 /www/wwwroot/genleri.com/index.php(57): Middleland\Dispatcher->dispatch() #71 {main}

**Comment by webtrees-pesz** [comment]
Hello Carmen,
I got the same error. PHP Version 7.3.13.
BR Peter

**Comment by JustCarmen** [comment]
Now the map function doesn't work anymore.

**Comment by JustCarmen** [comment]
I reverted the fix. Doesn't work as expected. I will have to investigate it further.
