### ISSUE TITLE
Open the image bar function, the database will be inexplicably stopped

### ISSUE THREAD

**Issue by kexuebin** [JustCarmen/webtrees-fancy-imagebar#48]
Open the image bar function, the database will be inexplicably stopped. Turn off the image bar function and the database is running normally.
mysql5.6.48

**Comment by JustCarmen** [comment]
Which version of webtrees, which version of the imagebar? And what do you mean by 'the database inexplicably stopped'? What error message do you get?

**Comment by kexuebin** [comment]
> 哪个版本的网络树，哪个版本的图像栏？“数据库莫名其妙地停止了”是什么意思？您得到什么错误信息？

wt2.0.8  and wt2.0.9 The same thing happens,Image bar 2.0.8 and Image bar 2.0.9 The same thing happens,The website can't be opened, a lot of code appears, and then enter the server to find that MySQL has stopped running, and the server only enjoys 1H, 1g, 1m

**Comment by JustCarmen** [comment]
Don't mix up versions. Use wt 2.0.9 and Fancy Imagebar 2.0.9. 

Post the error message because until now I don't have a clue what could be wrong.

**Comment by kexuebin** [comment]
> Don't mix up versions. Use wt 2.0.9 and Fancy Imagebar 2.0.9.
> 
> Post the error message because until now I don't have a clue what could be wrong.

wt2.0.9 and wt2.0.9 The same thing happens

**Comment by JustCarmen** [comment]
I've asked you multiple times to post the error message. I can't help you without that information.

**Comment by kexuebin** [comment]
> 我已多次要求您发布错误消息。没有这些信息，我无法帮助您。

RuntimeException: SQLSTATE[HY000] [2002] No such file or directory in /www/wwwroot/genstree/app/Http/Middleware/UseDatabase.php:114 Stack trace: #0 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #1 /www/wwwroot/genstree/app/Http/Middleware/BadBotBlocker.php(212): Middleland\Dispatcher->handle() #2 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #3 /www/wwwroot/genstree/app/Http/Middleware/RegisterFactories.php(72): Middleland\Dispatcher->handle() #4 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process() #5 /www/wwwroot/genstree/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle() #6 /www/wwwroot/genstree/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #7 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #8 /www/wwwroot/genstree/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #9 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #10 /www/wwwroot/genstree/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle() #11 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #12 /www/wwwroot/genstree/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle() #13 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #14 /www/wwwroot/genstree/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle() #15 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #16 /www/wwwroot/genstree/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #17 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #18 /www/wwwroot/genstree/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle() #19 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process() #20 /www/wwwroot/genstree/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #21 /www/wwwroot/genstree/index.php(57): Middleland\Dispatcher->dispatch() #22 {main}

**Comment by JustCarmen** [comment]
Ok, this helps to the extent that I don't think this is caused by the Fancy Imagebar. At least, the error is not coming from a module file but from a core webtrees file and I have no idea why this happens.

I will ask @fisharebest for help on this matter.

**Comment by fisharebest** [comment]
This error frequently means that you have the wrong value in `data/config.ini.php`.

If you have `dbhost=localhost`, try changing it to `dbhost=127.0.0.1`

But I do not understand how this error is connected to the fancyimagebar module.

This error occurs before we load the modules.

**Comment by kexuebin** [comment]
> 此错误通常表示您在中具有错误的值`data/config.ini.php`。
> 
> 如果有`dbhost=localhost`，请尝试将其更改为`dbhost=127.0.0.1`
> 
> 但是我不明白这个错误是如何连接到fancyimagebar模块的。
> 
> 在加载模块之前会发生此错误。



> 此错误通常表示您在中具有错误的值`data/config.ini.php`。
> 
> 如果有`dbhost=localhost`，请尝试将其更改为`dbhost=127.0.0.1`
> 
> 但是我不明白这个错误是如何连接到fancyimagebar模块的。
> 
> 在加载模块之前会发生此错误。

It has been changed to 127.0.0.1 config.ini There is no error. The image bar just started to run normally. After an hour, the database stopped inexplicably, and the above error occurred when visiting the website.

> This error frequently means that you have the wrong value in `data/config.ini.php`.
> 
> If you have `dbhost=localhost`, try changing it to `dbhost=127.0.0.1`
> 
> But I do not understand how this error is connected to the fancyimagebar module.
> 
> This error occurs before we load the modules.

It has been changed to 127.0.0.1 config.ini There is no error. The image bar just started to run normally. After an hour, the database stopped inexplicably, and the above error occurred when visiting the website.

**Comment by JustCarmen** [comment]
And this only occurs when the Fancy Imagebar is activated?

**Comment by kexuebin** [comment]
> 这仅在激活“花式图像栏”时发生吗？

Yes, the test closed the image bar, and the database has not stopped. But when I open the image bar, the database will stop. Do I think it is because my server configuration is too low?

**Comment by kexuebin** [comment]
> > 这仅在激活“花式图像栏”时发生吗？
> 
> 是的，测试关闭了图像栏，并且数据库尚未停止。但是，当我打开图像栏时，数据库将停止。我是否认为是因为我的服务器配置太低？

Just now, download the master under GitHub again, and wait for the database to stop again.

**Comment by kexuebin** [comment]
I also found a strange problem, my icon bar will show a lot of duplicate images, the control panel to confirm that there are no duplicate images

**Comment by JustCarmen** [comment]
> Do I think it is because my server configuration is too low?

I don't know. That might be the problem. The Fancy Imagebar uses some resources to manipulate the images on the fly.

> I also found a strange problem, my icon bar will show a lot of duplicate images, the control panel to confirm that there are no duplicate images.

That is by design. If there are fewer images available (without privacy restrictions) then needed to fill up the entire imagebar, the images are repeated.
