### ISSUE TITLE
Request to adapt to the rural theme

### ISSUE THREAD

**Issue by kexuebin** [JustCarmen/webtrees-fancy-imagebar#49]
thank you very much Carman

**Comment by JustCarmen** [comment]
This is already done and implemented in the [latest release](https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/tag/2.0.9).

Also see: https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/39 and: https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/de05d2d6ed985d56d90a6c5f29aece7474a5d0da

**Comment by kexuebin** [comment]
> 这已经在[最新版本中](https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/tag/2.0.9)完成并实现。
> 
> 另请参阅：[＃39](https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/39)和：[de05d2d](https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/de05d2d6ed985d56d90a6c5f29aece7474a5d0da)

After installing version 2.09, the rural theme image bar is out of bounds
