### ISSUE TITLE
resizing width

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-fancy-imagebar#52]
Perhaps the width of the fancy-imagebar should only be the width of a row. That looks more nice (for some themes).

**Comment by kexuebin** [comment]
#49

**Comment by arbor95** [comment]
I use the latest (2.0.9) and the issue is (still) with that version.
for F.A.B. I would like it with more width, for the other themes including Rural I'd like it smaller.
I don't know, if you can take the size from the <div class="row">

**Comment by JustCarmen** [comment]
#49 is solved. For the FAB theme see my comment here: #53

**Comment by arbor95** [comment]
I think I use the latest Rural.
I think the fancy Imagebar should not use the complete window size.

**Comment by JustCarmen** [comment]
> I think I use the latest Rural.
I think the fancy Imagebar should not use the complete window size.

I really don't know what your problem is. 

![image](https://user-images.githubusercontent.com/5641963/96360963-f364e200-1121-11eb-8075-aadcc911a5f3.png)

Looks good to me.

**Comment by arbor95** [comment]
Look at http://web.bild-raum.de/ and change theme :
![rural-at-http web bild-raum de ](https://user-images.githubusercontent.com/6124739/96361598-6cb30380-1127-11eb-8304-4e5a8d52a56c.jpg)

I can't change theme at Wij zijn familie.

**Comment by kexuebin** [comment]
> 查看http://web.bild-raum.de/并更改主题：
> ![http：// bill-raum ](https://user-images.githubusercontent.com/6124739/96361598-6cb30380-1127-11eb-8304-4e5a8d52a56c.jpg)
> 
> 我无法在Wij zijn familie更改主题。

Please download the master branch of GitHub

> 查看http://web.bild-raum.de/并更改主题：
> ![http：// bill-raum ](https://user-images.githubusercontent.com/6124739/96361598-6cb30380-1127-11eb-8304-4e5a8d52a56c.jpg)
> 
> 我无法在Wij zijn familie更改主题。

Please download the master branch of GitHub
https://github.91chifun.workers.dev//https://github.com/JustCarmen/webtrees-fancy-imagebar/archive/master.zip

**Comment by arbor95** [comment]
ok that looks good:
![2020-10-18 10_05_06-Window](https://user-images.githubusercontent.com/6124739/96361911-e4822d80-1129-11eb-84bb-4126e9110d3a.jpg)

**Comment by JustCarmen** [comment]
Seems like the problem is solved then.
