### ISSUE TITLE
FAB Theme issues with fancy image bar

### ISSUE THREAD

**Issue by makitso** [JustCarmen/webtrees-fancy-imagebar#53]
Carmen,
Some folks prefer that a theme use more of the monitor space that the default.  If they  set container-lg selector to 
max-width: 95%;  it works for all themes except F.A.B.  
See link for example https://www.amitys.com/future/index.php?route=%2Ffuture%2Ftree%2FDonaldDuck.ged#

Suggest this fix:
```
.wt-theme-fab .jc-fancy-imagebar {
overflow: visible;
}

[dir=ltr] .wt-theme-fab .jc-fancy-imagebar {
    margin-left: 0;
    margin-right: 0;
}
```

**Comment by JustCarmen** [comment]
If I do this, then it doesn't work anymore on the default FAB layout. I am sorry, but I can't keep everybody happy. If someone makes custom changes to a theme then he/she also should know how to adjust the Fancy Imagebar so it fits with their custom theme.

The default FAB theme is the only standard theme with a fixed width header. To adjust the Fancy Imagebar for that theme it also needs a fixed width. So it is clear that once the FAB theme is changed the Fancy Imagebar will not fit anymore.  Tell me how I can determine when the default FAB theme is used and when the extended version?  I don't see a class name or something that differs from the default. If there is a way to recognize which layout is used than maybe I could do something but at the moment I don't see how.

But I do like the used example gedcom :)

**Comment by JustCarmen** [comment]
As far as I can see this can be solved by using the build-in CSS/JS Module:

```
<style>    
.wt-theme-fab .jc-fancy-imagebar {
   max-width: 95% !important;
}
</style>`

**Comment by melizaa** [comment]
JustCarmen - Thanks for your comment on my example gedcom!
