### ISSUE TITLE
Fancy imagebar occationally crashes

### ISSUE THREAD

**Issue by ardhtu** [JustCarmen/webtrees-fancy-imagebar#54]
Hi,
I have wt 2.0.10, Just Light 2.0.9, Fancy Imagebar 2.0.9, PHP 7.4, all images are jpg.
On some of my photos I get this:
getimagesize(): Read error! …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:455
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, 'getimagesize():...', '/home/tunkkari/...', 455, Array)
#1 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(455): getimagesize('data/media/ingr...')
#2 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(480): JustCarmen\Webtrees\Module\FancyImagebarModule->loadImage('data/media/ingr...')
#3 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(332): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyThumb('data/media/ingr...', '80', '0')
#4 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(215): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyImagebar()
#5 …/modules_v4/justlight/resources/views/layouts/default.phtml(243): JustCarmen\Webtrees\Module\FancyImagebarModule->bodyContent()
#6 [internal function]: Fisharebest\Webtrees\View::{closure}(Object(JustCarmen\Webtrees\Module\FancyImagebarModule), '_jc-fancy-image...')
#7 …/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array)
#8 …/modules_v4/justlight/resources/views/layouts/default.phtml(244): Illuminate\Support\Collection->map(Object(Closure))

**Comment by JustCarmen** [comment]
I think this should be solved with this commit https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/d3781a7f23d3ed2392b99042b0d83bfd51d18fbb

If you still encounter the problem please let me know.
