### ISSUE TITLE
getimagesize(): Read error! 

### ISSUE THREAD

**Issue by DaPoHou** [JustCarmen/webtrees-fancy-imagebar#55]
After enabling the module, the website opens very slowly, almost unable to open.
The following error appears in the website log
`<b>getimagesize(): Read error! …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:459</b> #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8, &#039;getimagesize():...&#039;, &#039;/share/CACHEDEV...&#039;, 459, Array) <b>#1 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(459): getimagesize(&#039;data/media/\xE7\x8E\x8B\xE8...&#039;)</b> <b>#2 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(484): JustCarmen\Webtrees\Module\FancyImagebarModule-&gt;loadImage(&#039;data/media/\xE7\x8E\x8B\xE8...&#039;)</b> <b>#3 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(336): JustCarmen\Webtrees\Module\FancyImagebarModule-&gt;fancyThumb(&#039;data/media/\xE7\x8E\x8B\xE8...&#039;, &#039;80&#039;, &#039;0&#039;)</b> <b>#4 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(215): JustCarmen\Webtrees\Module\FancyImagebarModule-&gt;fancyImagebar()</b> <b>#5 …/modules_v4/wang/resources/views/layouts/default_www.snwsjz.com.phtml(339): JustCarmen\Webtrees\Module\FancyImagebarModule-&gt;bodyContent()</b> #6 [internal function]:`

**Comment by JustCarmen** [comment]
Related to: https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/54

I think this also is solved with commit d3781a7

If you still encounter the problem please let me know.
