### ISSUE TITLE
error when register as new user using an existing e-mail address

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-imagebar#59]
When I try to register as a new user (enter data in "Request a new user account" and press the "continue" button) there is an error message from fancy-imagebar, if I'm using an already existing e-mail address. Normally webtrees will show the home page with an error bar that this e-mail address is already used. If fancy-imagebar is activated, this results in the following error:
`
Error: Call to a member function id() on null in /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:234 Stack trace: #0 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/resources/views/layouts/default.phtml(65): JustCarmen\Webtrees\Module\FancyImagebarModule->headContent() #1 [internal function]: Fisharebest\Webtrees\View::{closure}(Object(JustCarmen\Webtrees\Module\FancyImagebarModule), '_jc-fancy-image...') #2 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array) #3 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/resources/views/layouts/default.phtml(66): Illuminate\Support\Collection->map(Object(Closure)) #4 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/View.php(189): include('/mnt/web312/a3/...') #5 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/View.php(286): Fisharebest\Webtrees\View->render() #6 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('layouts/default', Array) #7 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/ViewResponseTrait.php(58): view('layouts/default', Array) #8 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/RequestHandlers/RegisterPage.php(78): Fisharebest\Webtrees\Http\RequestHandlers\RegisterPage->viewResponse('register-page', Array) #9 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\RegisterPage->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11
`

**Comment by JustCarmen** [comment]
This is already solved with this commit: https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/7927d16758ed7a93d9aeadc58c0b609b90383b95

I've just released [a new version](https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/latest) which contains the fix
