### ISSUE TITLE
show on homepage only works only for first tree

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/webtrees-fancy-imagebar#66]
I have 4 trees inside of webtrees. The option "show on homepage only" works only on my first tree.
In the other 3 trees it is displayed on every single page.

**Comment by reteP-riS** [comment]
This option needs to be activated/deactivated on a per tree basis. First chose the tree, then activate/deactivate.

**Comment by HonkXL** [comment]
uuups.... Sorry.

**Comment by JustCarmen** [comment]
Glad it is solved.
