### ISSUE TITLE
Width limit

### ISSUE THREAD

**Issue by Ricch84** [JustCarmen/webtrees-fancy-imagebar#68]
Hello
I use actually the 2.0.7.2 version and i use too the rural theme
Is it possible to limit the width sise 
see this captur
![image](https://user-images.githubusercontent.com/82289039/114283651-175b0d80-9a4b-11eb-978d-61f564ff41de.png)

thanks you

**Comment by JustCarmen** [comment]
I think this is solved.

Tested with Fancy imagebar version 2.0.13 en Rural theme version 2.0.12-v.3 I can't reproduce this issue.

![image](https://user-images.githubusercontent.com/5641963/126878905-e221bcbf-486a-48bd-80ea-db0a46693816.png)
