### ISSUE TITLE
Update to the latest version, but still open the website very slowly, about 5-8 seconds to open the website

### ISSUE THREAD

**Issue by kexuebin** [JustCarmen/webtrees-fancy-imagebar#69]
Update to the latest version, but still open the website very slowly, about 5-8 seconds to open the website, close the image bar, everything is normal, there is no solution. The archaeological images are basically not compressed, most of them are more than 1m.

**Comment by arbor95** [comment]
Slow opening too, but think doesn't depend on the version.
Perhaps reducing the number of images to check helps
 or
 a delayed execution
 or
 caching some basics can help.

**Comment by JustCarmen** [comment]
Do you still experience the issue with the latest release?

**Comment by arbor95** [comment]
It is now quick, but only a black bar is shown. (Must I change some setup? my webtrees is still 2.0.16 . )
Console display (comes maybe not from imagebar):
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
Asset?asset=js%2Fscript.js&hash=1577685323:1 Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at Asset?asset=js%2Fscript.js&hash=1577685323:1

**Comment by ungeahnt** [comment]
> It is now quick, but only a black bar is shown. (Must I change some setup? my webtrees is still 2.0.16 . )

Go to the control panel and select the images you want to see. That's all ;)

Regarding the loading times: I had activated about 100 images today and the loading time of my website increased by about 1s with the module. That would have been just tolerable for me, but ...

... the error _"RuntimeException: SQLSTATE[HY000] [1203] User X already has more than 'max_user_connections' active connections"_ occurred frequently. 

I haven't found out yet on which value 'max_user_connections' is set on my system, but obviously the imagebar generates a lot of SQL-queries! Maybe this could be optimized? 

Right now I have about 30 images activated and with 2-3 visitors at the same time the website is running.

**Comment by arbor95** [comment]
Ok, I give it a try. Till now I had selected all images, about 500

**Comment by JustCarmen** [comment]
> It is now quick, but only a black bar is shown. (Must I change some setup? my webtrees is still 2.0.16 . )

I've made a separate issue of this (#81). This wasn't meant to be.

**Comment by JustCarmen** [comment]
> ... the error "RuntimeException: SQLSTATE[HY000] [1203] User X already has more than 'max_user_connections' active connections" occurred frequently.

Where does this error occurs?

> I haven't found out yet on which value 'max_user_connections' is set on my system, but obviously the imagebar generates a lot of SQL-queries! Maybe this could be optimized?

Good suggestion. I'll see what I can do.

**Comment by ungeahnt** [comment]
> 
> 
> > ... the error "RuntimeException: SQLSTATE[HY000] [1203] User X already has more than 'max_user_connections' active connections" occurred frequently.
> 
> Where does this error occurs?
> 
> > I haven't found out yet on which value 'max_user_connections' is set on my system, but obviously the imagebar generates a lot of SQL-queries! Maybe this could be optimized?
> 
> Good suggestion. I'll see what I can do.

I've moved this topic to a new issue: #85

**Comment by JustCarmen** [comment]
The changes made in the last release together with the latest changes made afterwards (https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/4dc4a0cd3ce6ac9065ef4e6d9bdb487b5a620767 and https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/65483a6ca2e19cf415d5935229e1ccf0c2b726d8) should boost performance further.

I will close this issue now. If you still have troubles please open a new issue.
