### ISSUE TITLE
More than one file in an media objects results in problems

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-imagebar#79]
1. I have many media objects which contain more than one file, for example, the original image and a cropped or edited version. In the image bar, both are shown. I would prefer to see only the first file in a media object (or having a solution for the following point 2).

![Screenshot (467)_LI](https://user-images.githubusercontent.com/6324175/133891432-260e20d9-bd11-458f-a52c-9291b4e9ce1b.jpg)

2. With the new version of your module (which is great!), it is possible to select and deselect every image. It looks like that it is possible to select the first file in a media object and to deselect the second file. But this doesn't work. After storing the selection, both files are selected or both are deselected. It would be great if the selection is based on media files and not on media objects; this would be a solution for the previous point 1.

![Screenshot (466)_LI](https://user-images.githubusercontent.com/6324175/133891491-f77d7bf9-1e79-4603-b684-b07e04743de1.jpg)

**Comment by JustCarmen** [comment]
Yes, I see what you mean. I don't use that feature much so I missed it. I'll see what I can do.
