### ISSUE TITLE
RuntimeException: SQLSTATE[HY000] [1203] User X already has more than 'max_user_connections' active connection

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-fancy-imagebar#85]
Regarding the loading times: I had activated about 100 images today and the loading time of my website increased by about 1s with the module. That would have been just tolerable for me, but ...

... the error _"RuntimeException: SQLSTATE[HY000] [1203] User X already has more than 'max_user_connections' active connections"_ occurred frequently. 

I haven't found out yet on which value 'max_user_connections' is set on my system, but obviously the imagebar generates a lot of SQL-queries! Maybe this could be optimized? 

Right now I have about 30 images activated and with 2-3 visitors at the same time the website is running.

_Originally posted by @ungeahnt in https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/69#issuecomment-922340570_

**Comment by ungeahnt** [comment]
_Originally posted by @JustCarmen in https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/69#issuecomment-922434633_

>> ... the error "RuntimeException: SQLSTATE[HY000] [1203] User X already has more than 'max_user_connections' active connections" occurred frequently.

>Where does this error occurs?

e.g on the mainpage, when it includes Html-blocks with statistics. You see the 'turning circle' for a short time and then the error appears instead of the block.

>> I haven't found out yet on which value 'max_user_connections' is set on my system, but obviously the imagebar generates a lot of SQL-queries! Maybe this could be optimized?

> Good suggestion. I'll see what I can do.

I'm using a shared webhosting and the variable 'max_user_connections' is set to 15 (and I can't change it). Is this a 'normal' value? I would have expected a higher value (like 200).

Do you have an idea how many connections (in relation with the max_user_connection) a pure webtrees (without fc-imagebar) generates and how many connections with fc-Imagebar will be opened (at the same time)? Do I create with every active module (like fc-imagebar and/or HTML-blocks) an additional connection? Can I check this myself somewhere?

**Comment by JustCarmen** [comment]
> ..., but obviously the imagebar generates a lot of SQL-queries!

I don't know where you've gotten this information from but the imagebar only uses a few sql queries each time to retrieve the settings and a query to retrieve the image objects from the database. I've checked this with the debugbar from webtrees development to confirm. I also don't see any duplicates. 

> I haven't found out yet on which value 'max_user_connections' is set on my system, but obviously the imagebar generates a lot of SQL-queries! Maybe this could be optimized?

> Good suggestion. I'll see what I can do.

Since I didn't found a surplus of sql queries related to the fancy imagebar, there is nothing to optimize.

> Do you have an idea how many connections (in relation with the max_user_connection) a pure webtrees (without fc-imagebar) generates and how many connections with fc-Imagebar will be opened (at the same time)? Do I create with every active module (like fc-imagebar and/or HTML-blocks) an additional connection? Can I check this myself somewhere?

I don't know. The number of connections is not the same as the number of queries. Maybe you should ask this question on the webtrees forum. There are probably people there with more technical knowledge regarding this subject than I have.

**Comment by JustCarmen** [comment]
See my last comment at #69. Since this issue is related I think this issue is also solved with the latest commits.

I will close this issue now. If you still have troubles please open a new issue.

**Comment by ungeahnt** [comment]
for completeness only:

>>     .., but obviously the imagebar generates a lot of SQL-queries!

>I don't know where you've gotten this information from but the imagebar only uses a few sql queries each time to retrieve the settings and a query to retrieve the image objects from the database. I've checked this with the debugbar from webtrees development to confirm. I also don't see any duplicates.

Sorry, this was the information that I get from my webhoster and I have not checked this myself. 

Last version (V2.1.2) with the image caching is really the "boost" optimization. 

Thanks a lot for this great module!
