### ISSUE TITLE
no imagebar shown after upload of gedcom file

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-fancy-imagebar#93]
Every time I upload the gedcom file, the images selected for the imagebar are unselected and no imagebar is shown.
If not all images shall be shown, the selection is a boring thing.
A block-selection makes that easier.

**Comment by arbor95** [comment]
again

**Comment by JustCarmen** [comment]
I cannot reproduce this. If I import a new Gedcom (overwriting a previous one), this has no impact on the fancy imagebar. The imagebar remains intact.

Assuming you are using the [latest version](https://github.com/JustCarmen/webtrees-fancy-imagebar/releases/latest) of this module, the only thing I can think of is that somehow the references differ. If a media object gets a new ID-number (Xref) when you do an export in your offline program than this could cause the imagebar to unload objects with non existing references.

Btw, there is an option to select/unselect all items in one go.  You'll find it between the blue info block and the page navigation.

**Comment by arbor95** [comment]
thanks for your late response. sure using the latest version. may be the reason is in the gedcom-file. It uses internal representation in the form
1 OBJE
2 FILE C:\<path>\<name>.jpg
3 FORM jpg
2 TITL <a description>
and not
a ref like
1 OBJE @X<number>@
I think webtrees converts on import.
I did not check the reference numbers that webtree generates.
But nearly all images are the same on next import.

Surely I know the quick checkbox for all images to show. It works only once, so it is rather a button than a checkbox. It is always unchecked at setup start. (The images surely stay checked. Only after import they are unchecked)

**Comment by JustCarmen** [comment]
> I think webtrees converts on import.
Yes, that makes sense. As far as I know, webtrees needs an Xref (the ID number between @..@) to handle media objects.
In your case, the Xref numbers are automatically generated and change with each import. 
Every time you select images on the Fancy Imagebar configuration page, the corresponding Xrefs are stored in the database, so the system knows which images you selected and will remember your selection.
But if the Xrefs change with each import, the numbers previously stored in the database will no longer match. So the system thinks you haven't selected any images yet. That is the reason why you do not see a check mark under the images. 

I can't help you with this. The module stores the Xrefs in the database and compiles the image bar based on them. When these numbers change there is no longer a reference point. In my opinion your only option is to re-select the desired images for the Fancy Imagebar after each import.

My advice would be to do the editing online. No need to re-import the Gedcom every time.

**Comment by arbor95** [comment]
Among other things: Edit in webtrees is a shit (meaning editing each tag separate, (clicking on the pencil and save) is a no go for me).
So I will use your checkbox-button (which is always unchecked, even if all pictures are checked)  as quickest solution.
Thanks for your work.

**Comment by JustCarmen** [comment]
> the site is https://freris.de where to send you a login?

I think you are referring to the [issue ](https://github.com/JustCarmen/webtrees-theme-justlight/issues/102) about the Justlight theme. This issue is about the Fancy Imagebar which is a different module.

Read my answer here: https://github.com/JustCarmen/webtrees-theme-justlight/issues/102
